#!/usr/bin/python3
# Based on a script by Eduardo Leggiero - https://www.leggiero.uk
# https://www.leggiero.uk/post/running-desktop-files-from-command-line/

from gi.repository import Gio
import sys
import os

def check_and_run(path, *uris):
     if os.path.isfile(path):
         try:
             launcher = Gio.DesktopAppInfo.new_from_filename(path)
             launcher.launch_uris(uris, None)
         except TypeError as e:
             pass
         except Exception as e:
             print(e)
         else:
             sys.exit()


def main(myname, desktop, *uris):
     d_file = desktop

     if not d_file.endswith(".desktop"):
         d_file = d_file + ".desktop"

     check_and_run(d_file)
     print("No starter found for", desktop)
     sys.exit(1)

if __name__ == "__main__":
     main(*sys.argv)

